language: objective-c
before_install:
 - export TZ=America/Chicago
 - npm install -g grunt-cli
install: npm install
before_script:
 - grunt shell:startOSPi
 - grunt test
 - grunt shell:stopOSPi
 - grunt shell:startDemo
 - grunt test
 - grunt shell:stopDemo
after_success:
 - ./node_modules/.bin/lcov-result-merger 'coverage/results-*.lcov' 'coverage/results.lcov'
 - cat coverage/results.lcov | ./node_modules/codecov.io/bin/codecov.io.js
 - cat coverage/results.lcov | ./node_modules/.bin/coveralls
script:
 - xctool -project source/osx/OpenSprinkler.xcodeproj -scheme OpenSprinkler -sdk macosx10.9 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""
notifications:
  on_failure: change
